### ISSUE TITLE
L10n

### ISSUE THREAD

**Issue by lsap** [Bohdan17-bit/Trading-Platform#2]
Hey Bohdan.

Please consider using https://jobs.dou.ua/companies/crowdin/ for the localization.

**Comment by Bohdan17-bit** [comment]
Hello, Isap!
Thank you for suggestion :)
I will be happy to cooperate in the future!

**Comment by lsap** [comment]
Can I put 'good first issue' label?

**Comment by Bohdan17-bit** [comment]
Isap, tell me in more detail what question you are considering?

**Comment by Bohdan17-bit** [comment]
Of course, any question can be created in the discussion tab!

**Comment by Bohdan17-bit** [comment]
OK.
